### PR TITLE
Added retropie.service

### PR DESCRIPTION
**Pull request by tvannahl**
With this changes retropie can be started as a systemd service. The unit
does replace the former `retropie.sh` including its
`retropie_watchdog.sh` by using systemds logic.

The service is configured so that every time retropie.service stops the
mediacenter.service will be started again regardless whenever
retropie.service stops or crashes. Further more it is now possible to
start and stop retropie in a clean way by using `systemctl start
retropie` and `systemctl stop retropie`.
Due to the `Conflict=mediacenter.service` within the retropie.service
xbmc and retropie will not run at the same time.

This patch does not include the former cec-client fix nor the hyperion
fix because I could not find details about the origins of those fixes.

### CODE REVIEW

**Comment by mcobit** [comment]
Hello,
That is a good idea. If I remember correctly, I started with this approach some years ago, but somethig kept me from doing it that way. But right now I can't remember what it was.
I will definately test your approach and see if nothing interferes.

Did you test this with a fresh installation, too?

Also not sure if starting emulationstation from it's binary location is a good idea as retropie does it with a script in /usr/bin. (see here: https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/emulationstation.sh) I want to make as few changes to the original retropie as possible.

**Comment by mcobit** [comment]
And of course: Thank you for your contribution!

**Comment by tvannahl** [comment]
I checked the installation routine and it did not work. Because of that I am closing the merge request for now. Modifications to the installation are currently hard to test, since I need to make modifications for beeing able to test. If I do make those modifications there is no point on which I can guarantee that it will work if I switch the links to upstream.

Regarding the ``emulationstation.sh``: I checked the script and would recommend that the retrosmc installed should be refined to execute that installation passage in ``emulationstation.sh`` so that the ``retropie.service`` can later execute the script in ``/usr/bin/emulationstation``. I would be ready do realize that retrosmc installer together with you. Maybe we could meet on a chat/voice-chat platform to discuss details.
Would be great to have a better testing platform for installlation and verification :-).

And thanks for the welcome!

**Comment by mcobit** [comment]
I need to find some time for that. Freetime is rare those days unfortunately.

The installer already does create the script in /usr/bin.

**Comment by tvannahl** [comment]
I do feel with you. I could probably write a feature and implementation proposal. Then the only thing you needed to do would be to criticize the ideas you don't like and speak for ideas you favor or outline problems you see.

From that we would benefit both I think. You could help with minimal time efford and I could help to improve the overall experience of retropie on osmc without the need to fork and maximum chance of merge.

Shall I create a new issue regarding those ideas including my feature and implementation proposals?

**Comment by mcobit** [comment]
Hi. If you got some time today we could probably chat a bit about your ideas. I'love to have collaborators on this and I like the service based starting.

**Pull request closed without merging**
